#!/bin/bash
SCRIPT_DIR="$(dirname $0)"
# For production, create application.properties in the same dir as "culinary" script
java -cp $SCRIPT_DIR'/target/dependency/*':$SCRIPT_DIR'/target/classes' com.hendyirawan.smartroad.DaemonApplication "$@"
